// Generate a browser- AND Node-safe TS module from the static mapping JSON.
// The JSON (data/bijoy-sutonnymj.json) stays the schema-validated source of
// truth; this emits src/engine/mapping.generated.ts so the engine imports the
// data as a plain module — no node:fs, so it bundles for the Word task pane and
// still runs under the Node corpus gate. Run via `npm run generate`.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const json = readFileSync(join(root, 'data', 'bijoy-sutonnymj.json'), 'utf8');
JSON.parse(json); // fail fast on malformed data

const out = `// AUTO-GENERATED by tools/gen-mapping.mjs from data/bijoy-sutonnymj.json.
// Do not edit by hand. Regenerate with \`npm run generate\`.
import type { MappingProfile } from './contracts.js';

export const profile: MappingProfile = ${json.trim()} as MappingProfile;
`;
writeFileSync(join(root, 'src', 'engine', 'mapping.generated.ts'), out);
console.log('Wrote src/engine/mapping.generated.ts from data/bijoy-sutonnymj.json');
